# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/arty_eth.xdc

# Block Designs: bd/TOP_ARTY_ETH/TOP_ARTY_ETH.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH || ORIG_REF_NAME==TOP_ARTY_ETH} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_clk_wiz_0_0/TOP_ARTY_ETH_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_clk_wiz_0_0 || ORIG_REF_NAME==TOP_ARTY_ETH_clk_wiz_0_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_mig_7series_0_0/TOP_ARTY_ETH_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_mig_7series_0_0 || ORIG_REF_NAME==TOP_ARTY_ETH_mig_7series_0_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_microblaze_0_0/TOP_ARTY_ETH_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_microblaze_0_0 || ORIG_REF_NAME==TOP_ARTY_ETH_microblaze_0_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_dlmb_v10_0/TOP_ARTY_ETH_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_dlmb_v10_0 || ORIG_REF_NAME==TOP_ARTY_ETH_dlmb_v10_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_ilmb_v10_0/TOP_ARTY_ETH_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_ilmb_v10_0 || ORIG_REF_NAME==TOP_ARTY_ETH_ilmb_v10_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_dlmb_bram_if_cntlr_0/TOP_ARTY_ETH_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TOP_ARTY_ETH_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_ilmb_bram_if_cntlr_0/TOP_ARTY_ETH_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TOP_ARTY_ETH_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_lmb_bram_0/TOP_ARTY_ETH_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_lmb_bram_0 || ORIG_REF_NAME==TOP_ARTY_ETH_lmb_bram_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_xbar_0/TOP_ARTY_ETH_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_xbar_0 || ORIG_REF_NAME==TOP_ARTY_ETH_xbar_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_pc_4/TOP_ARTY_ETH_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_pc_4 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_pc_4} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_us_0/TOP_ARTY_ETH_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_us_0 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_us_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_us_1/TOP_ARTY_ETH_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_us_1 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_us_1} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_us_2/TOP_ARTY_ETH_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_us_2 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_us_2} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_ds_0/TOP_ARTY_ETH_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_ds_0 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_ds_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_pc_0/TOP_ARTY_ETH_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_pc_0 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_pc_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_ds_1/TOP_ARTY_ETH_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_ds_1 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_ds_1} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_pc_1/TOP_ARTY_ETH_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_pc_1 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_pc_1} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_ds_2/TOP_ARTY_ETH_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_ds_2 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_ds_2} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_pc_2/TOP_ARTY_ETH_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_pc_2 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_pc_2} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_ds_3/TOP_ARTY_ETH_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_ds_3 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_ds_3} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_auto_pc_3/TOP_ARTY_ETH_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_auto_pc_3 || ORIG_REF_NAME==TOP_ARTY_ETH_auto_pc_3} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_microblaze_0_axi_periph_0/TOP_ARTY_ETH_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_microblaze_0_axi_periph_0 || ORIG_REF_NAME==TOP_ARTY_ETH_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_microblaze_0_axi_intc_0/TOP_ARTY_ETH_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_microblaze_0_axi_intc_0 || ORIG_REF_NAME==TOP_ARTY_ETH_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_microblaze_0_xlconcat_0/TOP_ARTY_ETH_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_microblaze_0_xlconcat_0 || ORIG_REF_NAME==TOP_ARTY_ETH_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_mdm_1_0/TOP_ARTY_ETH_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_mdm_1_0 || ORIG_REF_NAME==TOP_ARTY_ETH_mdm_1_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_rst_mig_7series_0_83M_0/TOP_ARTY_ETH_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==TOP_ARTY_ETH_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_axi_ethernetlite_0_0/TOP_ARTY_ETH_axi_ethernetlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_axi_ethernetlite_0_0 || ORIG_REF_NAME==TOP_ARTY_ETH_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_axi_uartlite_0_0/TOP_ARTY_ETH_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_axi_uartlite_0_0 || ORIG_REF_NAME==TOP_ARTY_ETH_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_axi_timer_0_0/TOP_ARTY_ETH_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_ARTY_ETH_axi_timer_0_0 || ORIG_REF_NAME==TOP_ARTY_ETH_axi_timer_0_0} -quiet] -quiet

# XDC: e:/ARTY_projects/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/TOP_ARTY_ETH/TOP_ARTY_ETH_ooc.xdc
