# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Clock_cnst.xdc

# Block Designs: bd/TOP_UART/TOP_UART.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART || ORIG_REF_NAME==TOP_UART} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_microblaze_0_0/TOP_UART_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_microblaze_0_0 || ORIG_REF_NAME==TOP_UART_microblaze_0_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_dlmb_v10_0/TOP_UART_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_dlmb_v10_0 || ORIG_REF_NAME==TOP_UART_dlmb_v10_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_ilmb_v10_0/TOP_UART_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_ilmb_v10_0 || ORIG_REF_NAME==TOP_UART_ilmb_v10_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_dlmb_bram_if_cntlr_0/TOP_UART_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TOP_UART_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_ilmb_bram_if_cntlr_0/TOP_UART_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TOP_UART_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_lmb_bram_0/TOP_UART_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_lmb_bram_0 || ORIG_REF_NAME==TOP_UART_lmb_bram_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_xbar_0/TOP_UART_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_xbar_0 || ORIG_REF_NAME==TOP_UART_xbar_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_microblaze_0_axi_periph_0/TOP_UART_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_microblaze_0_axi_periph_0 || ORIG_REF_NAME==TOP_UART_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_microblaze_0_axi_intc_0/TOP_UART_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_microblaze_0_axi_intc_0 || ORIG_REF_NAME==TOP_UART_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_microblaze_0_xlconcat_0/TOP_UART_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_microblaze_0_xlconcat_0 || ORIG_REF_NAME==TOP_UART_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_mdm_1_0/TOP_UART_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_mdm_1_0 || ORIG_REF_NAME==TOP_UART_mdm_1_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_clk_wiz_1_0/TOP_UART_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_clk_wiz_1_0 || ORIG_REF_NAME==TOP_UART_clk_wiz_1_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_rst_clk_wiz_1_100M_0/TOP_UART_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==TOP_UART_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/TOP_UART/ip/TOP_UART_axi_uartlite_0_0/TOP_UART_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_UART_axi_uartlite_0_0 || ORIG_REF_NAME==TOP_UART_axi_uartlite_0_0} -quiet] -quiet

# XDC: d:/MYGITHUB/MYCODES/FPGA/IF_UART/UART/UART.gen/sources_1/bd/TOP_UART/TOP_UART_ooc.xdc
