# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MYGITHUB/MYCODES/FPGA/IF_UART/UART/UART.srcs/sources_1/bd/TOP_UART/ip/TOP_UART_lmb_bram_0/TOP_UART_lmb_bram_0.xci
# IP: The module: 'TOP_UART_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MYGITHUB/MYCODES/FPGA/IF_UART/UART/UART.gen/sources_1/bd/TOP_UART/ip/TOP_UART_lmb_bram_0/TOP_UART_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_UART_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/MYGITHUB/MYCODES/FPGA/IF_UART/UART/UART.srcs/sources_1/bd/TOP_UART/ip/TOP_UART_lmb_bram_0/TOP_UART_lmb_bram_0.xci
# IP: The module: 'TOP_UART_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MYGITHUB/MYCODES/FPGA/IF_UART/UART/UART.gen/sources_1/bd/TOP_UART/ip/TOP_UART_lmb_bram_0/TOP_UART_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_UART_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
