# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/ARTY_projects/ARTY_ETH/ARTY_ETH.srcs/sources_1/bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_dlmb_v10_0/TOP_ARTY_ETH_dlmb_v10_0.xci
# IP: The module: 'TOP_ARTY_ETH_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ARTY_projects/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_dlmb_v10_0/TOP_ARTY_ETH_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_ARTY_ETH_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/ARTY_projects/ARTY_ETH/ARTY_ETH.srcs/sources_1/bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_dlmb_v10_0/TOP_ARTY_ETH_dlmb_v10_0.xci
# IP: The module: 'TOP_ARTY_ETH_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/ARTY_projects/ARTY_ETH/ARTY_ETH.gen/sources_1/bd/TOP_ARTY_ETH/ip/TOP_ARTY_ETH_dlmb_v10_0/TOP_ARTY_ETH_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TOP_ARTY_ETH_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
