# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/TOP_MTDS/TOP_MTDS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS || ORIG_REF_NAME==TOP_MTDS} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_microblaze_0_0/TOP_MTDS_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_microblaze_0_0 || ORIG_REF_NAME==TOP_MTDS_microblaze_0_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_dlmb_v10_0/TOP_MTDS_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_dlmb_v10_0 || ORIG_REF_NAME==TOP_MTDS_dlmb_v10_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_ilmb_v10_0/TOP_MTDS_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_ilmb_v10_0 || ORIG_REF_NAME==TOP_MTDS_ilmb_v10_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_dlmb_bram_if_cntlr_0/TOP_MTDS_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TOP_MTDS_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_ilmb_bram_if_cntlr_0/TOP_MTDS_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TOP_MTDS_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_lmb_bram_0/TOP_MTDS_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_lmb_bram_0 || ORIG_REF_NAME==TOP_MTDS_lmb_bram_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_xbar_0/TOP_MTDS_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_xbar_0 || ORIG_REF_NAME==TOP_MTDS_xbar_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_microblaze_0_axi_periph_0/TOP_MTDS_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_microblaze_0_axi_periph_0 || ORIG_REF_NAME==TOP_MTDS_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_microblaze_0_axi_intc_0/TOP_MTDS_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_microblaze_0_axi_intc_0 || ORIG_REF_NAME==TOP_MTDS_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_microblaze_0_xlconcat_0/TOP_MTDS_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_microblaze_0_xlconcat_0 || ORIG_REF_NAME==TOP_MTDS_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_mdm_1_0/TOP_MTDS_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_mdm_1_0 || ORIG_REF_NAME==TOP_MTDS_mdm_1_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_clk_wiz_1_0/TOP_MTDS_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_clk_wiz_1_0 || ORIG_REF_NAME==TOP_MTDS_clk_wiz_1_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_rst_clk_wiz_1_100M_0/TOP_MTDS_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==TOP_MTDS_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/TOP_MTDS/ip/TOP_MTDS_PmodMTDS_0_0/TOP_MTDS_PmodMTDS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TOP_MTDS_PmodMTDS_0_0 || ORIG_REF_NAME==TOP_MTDS_PmodMTDS_0_0} -quiet] -quiet

# XDC: e:/Projects/MTDS/MTDS.gen/sources_1/bd/TOP_MTDS/TOP_MTDS_ooc.xdc
